### ISSUE TITLE
Read timeout: Unexpected exception caught!

### ISSUE THREAD

**Issue by tbressler** [tbressler/waterrower-core#10]
After a short amount of time the following exception is thrown:

```
13:16:58.245 [oioEventLoopGroup-2-1] [] ERROR: Unexpected exception caught in !
com.fazecast.jSerialComm.SerialPortTimeoutException: The read operation timed out before any data was returned.
	at com.fazecast.jSerialComm.SerialPort$SerialPortInputStream.read(SerialPort.java:1488) ~[jSerialComm-2.6.2.jar:2.6.2]
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:211) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1124) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.oio.OioByteStreamChannel.doReadBytes(OioByteStreamChannel.java:107) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:127) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:40) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:69) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
13:16:58.253 [oioEventLoopGroup-2-1] [] ERROR: An error occurred! Error code is COMMUNICATION_FAILED.
13:16:58.254 [oioEventLoopGroup-2-1] [] WARN : Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@21f98799(failure: io.netty.channel.StacklessClosedChannelException), unnotified cause: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:864) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:69) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.56.Final.jar:4.1.56.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
13:16:58.255 [oioEventLoopGroup-2-1] [] WARN : Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@3ec9eb72(failure: io.netty.channel.StacklessClosedChannelException), unnotified cause: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

Additionally, the port was not closed correctly.

**Comment by tbressler** [comment]
Due to a read timeout the WaterRower gets disconnected.
The value for read timeout is maybe to low for the WaterRower.
