### ISSUE TITLE
Reconnect still fails on Windows

### ISSUE THREAD

**Issue by tbressler** [tbressler/waterrower-core#18]
The reconnect after the WaterRower was disconnected still fails.

**Comment by tbressler** [comment]
Log:

```
[oioEventLoopGroup-2-1] WARN WaterRowerLibrary - Couldn't send exit communication message! Can not send message 'ExitCommunicationMessage{}'!
[oioEventLoopGroup-2-1] WARN WaterRowerLibrary - Couldn't disconnect!Can not disconnect!
[pool-2-thread-1] INFO WaterRowerLibrary - Auto-connecting serial port 'COM3'.
[oioEventLoopGroup-2-1] ERROR WaterRowerLibrary - Unexpected exception caught in serial handler!
com.fazecast.jSerialComm.SerialPortTimeoutException: The read operation timed out before any data was returned.
	at com.fazecast.jSerialComm.SerialPort$SerialPortInputStream.read(SerialPort.java:1488)
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:211)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1124)
	at io.netty.channel.oio.OioByteStreamChannel.doReadBytes(OioByteStreamChannel.java:107)
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:127)
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:40)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:69)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
[oioEventLoopGroup-2-1] WARN WaterRowerLibrary - Channel can not be closed!
[oioEventLoopGroup-2-1] ERROR WaterRowerLibrary - An error occurred! Error code is COMMUNICATION_FAILED.
[oioEventLoopGroup-2-1] WARN WaterRowerLibrary - Couldn't disconnect!Service is not connected! Can not disconnect.
[pool-2-thread-1] INFO WaterRowerLibrary - Serial port found: COM3
[pool-2-thread-1] INFO WaterRowerLibrary - Auto-connecting serial port 'COM3'.
[pool-1-thread-1] WARN WaterRowerLibrary - The device type was not confirmed yet!
[oioEventLoopGroup-2-1] ERROR WaterRowerLibrary - Unexpected exception caught in serial handler!
com.fazecast.jSerialComm.SerialPortTimeoutException: The read operation timed out before any data was returned.
	at com.fazecast.jSerialComm.SerialPort$SerialPortInputStream.read(SerialPort.java:1488)
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:211)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1124)
	at io.netty.channel.oio.OioByteStreamChannel.doReadBytes(OioByteStreamChannel.java:107)
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:127)
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:40)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:69)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
