### ISSUE TITLE
JDK11 

### ISSUE THREAD

**Issue by vojkny** [tbressler/waterrower-core#6]
The code unfortunately relies on JDK8 method `CommPortIdentifier.getPortIdentifiers()` which returns `null` on JDK11. I tried to replace this call, unfortunately it gets deeper, as the tool is heavily used within the whole codebase. 

It would be great one day to have this available on JDK11+ which is standard now.

Thanks!

**Comment by tbressler** [comment]
Unfortunately the problem comes from the netty framework and the RXTX transport layer I use for serial communication with the WaterRower. It seems that the RXTX transport layer is no longer maintained by the netty team (see [Mark transport-rxtx as `@deprecated`](https://github.com/netty/netty/issues/7199)). 

In commit 414ada9f I updated the netty and RXTX versions. I'm not able to test it right now. @knyttl  Can you please try if it works with JDK11 and give me feedback?

Thanks

**Comment by vojkny** [comment]
I will try later today, but as far as I can see, the RXTX layer still uses the JDK8 API, so we would probably have to completely replace it :/

**Comment by vojkny** [comment]
Note the `@Deprecated` commit you mention only adds `@Deprecated` annotations but does not replace it with better solution :/

**Comment by vojkny** [comment]
```
Exception in thread "main" java.lang.NoSuchMethodError: gnu.io.CommPortIdentifier.open(Ljava/lang/String;I)Lgnu/io/CommPort;
	at io.netty.channel.rxtx.RxtxChannel.doConnect(RxtxChannel.java:78)
	at io.netty.channel.rxtx.RxtxChannel$RxtxUnsafe.connect(RxtxChannel.java:163)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:69)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Now it does not work at all :/

**Comment by tbressler** [comment]
Ah okay, I used the wrong RXTX library. I fixed this issue with commit 62528b1.
But as you mentioned before, the RXTX layer still uses the JDK8 API. So the new netty version doesn't fix our problem. I will try to find a quick solution in the next weeks. *fingers crossed*

**Comment by vojkny** [comment]
offtopic – I don't know how to send you a message here – I mention your lib here: https://medium.com/@knyttl/waterrower-what-a-rower-b93966895fe

**Comment by tbressler** [comment]
offtopic - Nice project, I'm very happy to see that someone uses my library for his projects. Great idea to use distances from the real world :-) Keep going!

**Comment by tbressler** [comment]
I replaced the RXTX library with the jSerialComm library. 
This should fix the issue with the JDK now.
Please check out tag v0.10.1.
